### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by gorborukov** [Firework-Games-AI-Division/dmt-meshes#3]
Ubuntu 20.04, Blender 3.4.1
looks like installing dependencies is not working properly:

```
  Cloning https://github.com/Firework-Games-AI-Division/point-e (to revision main) to /tmp/pip-req-build-ggjhtz1v
  Running command git clone --filter=blob:none --quiet https://github.com/Firework-Games-AI-Division/point-e /tmp/pip-req-build-ggjhtz1v
  Resolved https://github.com/Firework-Games-AI-Division/point-e to commit c1e83d1336928ede4595c9d2bfa036ae41235f4c
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-ggjhtz1v/setup.py", line 11, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tolmanneo** [comment]
Hey thanks @gorborukov for using DMT Meshes. The .zip file is compiled it on Windows so that may be the reason why there is the error.

To make it works on Ubuntu, try this:
   To install dependencies locally, follow these steps: 
   
   * Open the Preferences window in Blender 
   
   * Check the box to enable Interface > Display > Developer Extras 
   
   * Proceed to install dependencies for development under Add-ons > DMT Meshes > Development Tools 
   
   * This will download all pip dependencies for the selected platform into .python_dependencies
   
   Let me know if it does not work.

**Comment by tolmanneo** [comment]
So the problem is that when installing point-e, python does not look into folder /.dependencies for torch module. 
I only tested on Windows, I will try to test this on Ubuntu later today. Thanks for raising the issue!

**Comment by gorborukov** [comment]
hi @tolmanneo , thanks for answering. I just completed all the steps you listed, and got an error, a fragment of which I posted above. In any case, I will try to solve it myself, but I will be grateful if you can test this on Ubuntu.

**Comment by tolmanneo** [comment]
Actually install from scratch is a bit tricky. 
In the meantime, you can try this:
   - Clone this repo: https://github.com/Firework-Games-AI-Division/point-e 
   - At line 9 in [setup.py](https://github.com/Firework-Games-AI-Division/point-e), add `sys.path.insert(0, <path_to_folder_/.dependencies_of_DMT_meshes>) `
   - Assume that you already has torch-cu11.7 installed into your .dependencies (which you should have even the installation above is failed), you can just run `pip install setup.py` from the point-e folder, then point-e will be compiled and move to .dependencies.
   - 
 Let me know if it works.

**Comment by Cubey42** [comment]
I'm getting this error on windows as well, I can't seem to get past it.
